channels:
  - conda-forge
dependencies:
  - conda-cpp>=5.2
  - python==3.7
  - matplotlib
  - pybind11
  # for docs generation
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - gxx_linux-64
  - libgcc
  - pytest
  - pip:
    - nbsphinx
